spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sber_library?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
  thymeleaf:
    mode: HTML
server:
  error:
    whitelabel:
      enabled: false